### PR TITLE
Use Promise instead of PromiseOrNot, since these have to be asynchronous

### PR DESCRIPTION
**Pull request by roblourens**
Is there any case where these could be synchronous? I don't see why PromiseOrNot would be used here.

### CODE REVIEW

**Comment by roblourens** [comment]
Hey @nojvek can you take a look at this?

**Comment by nojvek** [comment]
Will do. Thanks for PR.

**Comment by nojvek** [comment]
You will need to git pull and rebuild with your changes.   Changes in src/protocolToCrdp.ts look good. 

The PromiseOrNot was more for server. noice-json-rpc accepts expose commands which are synchronous. You are right, the client will always be async.

Are you going to use async-await in vscode-chrome-debug?

**Comment by roblourens** [comment]
Oh, that makes sense. In the server case I'm imagining, where you have a protocol adapter, it would still be asynchronous, but could be sync in other cases. Hopefully this is ok for now since casting every call to Promise would be annoying.

Not using async/await for back-compat until most people are using a version of vscode that will have a Node version that supports it.

**Comment by nojvek** [comment]
for crdp.d.ts, it should be fine. No one is using as a server yet. Let me know when you've updated your PR. I'll merge it and publish a new version

**Comment by roblourens** [comment]
@nojvek updated, thanks

**Comment by nojvek** [comment]
Published 1.2.20161007

**Pull request merged**
